name: Run Bruno Collection

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:  # Enables manual triggering of the workflow

jobs:
  run-bruno:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Run Bruno Collection
        run: |
        
          cd "C:\Users\TelangLaxmanVishnu(D\Laxman\API_harness\Harness_Integration"
          set NODE_TLS_REJECT_UNAUTHORIZED=0
          bru run --insecure