name: Run Bruno Collection

on:
  push:
    branches:
      - API_Automation_DEV
  pull_request:
    branches:
      - API_Automation_DEV
  workflow_dispatch:  # Enables manual triggering of the workflow

jobs:
  run-bruno:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Run Bruno Collection
        run: |
          set NODE_TLS_REJECT_UNAUTHORIZED=0
          
          bru run --insecure --reporter-json ./reports/results.json --reporter-html ./reports/results.html
      - name: Upload Reports
        uses: actions/upload-artifact@v4.6.2
        with:
         name: bruno-reports
         path: ./reports/